### PR TITLE
Initial Clockwork site design work

### PR DESCRIPTION
**Pull request by joshdura**
Not ready for merge, as I haven't made a pass at the forums, but the general look and feel is here. Also need to fix these merge conflicts.

### CODE REVIEW

**Comment by joshdura** [comment]
@jonsimington Not ready for merge unless you are willing to deal with forums weirdness. Lemme know if you have any comments so far.

**Comment by joshdura** [comment]
@jonsimington This is ready for review/merge. The forums style have a basic style applied to them. It's going to be an ongoing process, but this should be good enough for the live site I think. Let me know if I missed anything and I will slap a style on it.

**Comment by jonsimington** [comment]
Oooooh, hype!  I'll take a look this afternoon. 



—

**Comment by jonsimington** [comment]
@joshdura Looks pretty good.  

There are a couple of changes that I'm going to make:

* all links should be red, #900 imo
* keeping the label-default styling.  It provides a nice contrast where it is used
* I made wells background-color #333 because there was a lot of empty space
* changed label-warning's background-color to #900 to match the theme
* fixed some hover colors

**Pull request merged**
